### ISSUE TITLE
Enable to create embed.

### ISSUE THREAD

**Issue by yppdr** [Markoudstaal/node-red-contrib-discord-advanced#16]
After installing the plugin, I try to create an embed message. After several tests (even with the json provided as an example) I still have these two messages in my debug console.

![image](https://user-images.githubusercontent.com/1734599/147857384-16f58a04-372b-49bb-a496-f133f45f4550.png)

- Node-Red V2.1.4
- Node V16

**Comment by Markoudstaal** [comment]
This is my bad for not updating the documentation, sorry! The new version of discord handles embeds a bit different. Instead of the embed being the full message it's something you add to a message. Therefore you can now always have the msg.payload be some kind of text and add embeds to it. 

To send an embed now you'll have to set msg.embed to the embed object or an array of objects.

![image](https://user-images.githubusercontent.com/7512733/147857601-388d8ea7-6e7f-469a-86a8-88def011f911.png)
