### ISSUE TITLE
Discord Sharding

### ISSUE THREAD

**Issue by alokt** [Markoudstaal/node-red-contrib-discord-advanced#69]
Hi @javis86 thank you for this amzing node-red tool. 

Wanted to start a discussion related to sharding. Once bot will reach to more than 1000 guilds we also need to do sharding. 

**Auto sharding**
  `const client = new Client({ shardCount: "auto" });` 
is a quick solution for some time.

Is there any plan to support `ShardingManager`? Happy to contribute.

**Comment by javis86** [comment]
I think it´s possible to add internal Sharding without any impact of the current functioning.
Would SharingManager work through several nodered instances? 
Do you have some experience executing ShardingManager to run the shards in differents containers/VMs? This is in order to evaluate the correct functioning if it is implemented.

**Comment by javis86** [comment]
It could be added

**Comment by javis86** [comment]
Done in 3.4.1
